name: Discolight Commit Tests

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Pylint and Flake8
        run: ./lint.sh     
            
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    name: Tests (Python ${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: ./test.sh
